name: Build & Deploy
on:
  push:
    branches: [main]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          script: cd ${{ secrets.PATH }} && ${{ secrets.ENV_FILE }} > .env && git pull && docker-compose up --build -d
